apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: scholar-spark-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
{{- define "imagePullSecret" }}
{{- printf "{\"auths\": {\"ghcr.io\": {\"auth\": \"%s\"}}}" (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
{{- end }}
