# Default configuration
image:
  repository: ghcr.io/scholar-spark/scholarsparkauth/auth-service
  tag: latest
  pullPolicy: IfNotPresent

# Add credentials section for GitHub Container Registry
imageCredentials:
  username: ""
  password: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

database:
  host: postgres
  port: 5432
  name: auth
  user: user
  password: password

jwt:
  secretKey: "your-secret-key-here"

observability:
  tempo:
    enabled: true
    endpoint: http://tempo:4318

redis:
  enabled: true
  url: "redis://redis:6379/0"
